apiVersion: v2
name: grafana
description: Grafana dashboards for AI Platform
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: "8.x"
